// Records a ~3-minute captioned hackathon demo of CrisisPilot. Injects an
// on-screen caption bar (recorded into the video) that calls out each integration
// — Gemini, Google Cloud Agent Builder (ADK), and the Dynatrace MCP server — as
// the multi-agent investigation streams live.
const { chromium } = require('playwright');

const BACKEND = 'http://localhost:8000';
const FRONTEND = 'http://localhost:3000';
const VIDEO_DIR = '/Users/supriyarai/Desktop/crisispilot/demo-recorder/videos';
const W = 1600, H = 900;

const PACE = 1.2; // stretch all dwell times to land the video near ~3 minutes
const sleep = (ms) => new Promise((r) => setTimeout(r, Math.round(ms * PACE)));

async function apiTrigger(label) {
  try {
    const r = await fetch(`${BACKEND}/api/incidents/trigger`, { method: 'POST' });
    const j = await r.json();
    console.log(`[${label}] ${j.id} — ${j.title} (${j.severity})`);
  } catch (e) {
    console.log(`[${label}] trigger error: ${e.message}`);
  }
}

// Inject (idempotently) a caption bar and set its text. `chip` is a small label
// shown left of the caption (e.g. the integration name).
async function caption(page, text, chip = '') {
  await page.evaluate(
    ({ text, chip }) => {
      let bar = document.getElementById('cp-cap');
      if (!bar) {
        bar = document.createElement('div');
        bar.id = 'cp-cap';
        bar.style.cssText = [
          'position:fixed', 'left:50%', 'bottom:36px', 'transform:translateX(-50%)',
          'z-index:2147483647', 'display:flex', 'align-items:center', 'gap:12px',
          'max-width:80vw', 'padding:14px 22px', 'border-radius:14px',
          'background:rgba(8,12,20,0.86)', 'backdrop-filter:blur(8px)',
          'border:1px solid rgba(120,160,255,0.35)',
          'box-shadow:0 8px 40px rgba(0,0,0,0.55)',
          'font-family:Inter,system-ui,-apple-system,sans-serif',
          'color:#eaf0ff', 'font-size:26px', 'font-weight:600', 'letter-spacing:0.2px',
          'opacity:0', 'transition:opacity 350ms ease',
        ].join(';');
        const c = document.createElement('span');
        c.id = 'cp-cap-chip';
        c.style.cssText = [
          'font-size:15px', 'font-weight:700', 'text-transform:uppercase',
          'letter-spacing:1px', 'padding:5px 11px', 'border-radius:8px',
          'background:linear-gradient(90deg,#3b82f6,#22d3ee)', 'color:#06121f',
          'white-space:nowrap',
        ].join(';');
        const t = document.createElement('span');
        t.id = 'cp-cap-text';
        bar.appendChild(c);
        bar.appendChild(t);
        document.body.appendChild(bar);
      }
      const chipEl = document.getElementById('cp-cap-chip');
      const txtEl = document.getElementById('cp-cap-text');
      chipEl.style.display = chip ? 'inline-block' : 'none';
      chipEl.textContent = chip;
      txtEl.textContent = text;
      bar.style.opacity = '1';
    },
    { text, chip }
  );
}

async function pan(page, totalY, steps = 12, pause = 300) {
  const dy = Math.round(totalY / steps);
  for (let i = 0; i < steps; i++) { await page.mouse.wheel(0, dy); await sleep(pause); }
}

async function clickByText(page, text) {
  try { await page.getByText(text, { exact: false }).first().click({ timeout: 2500 }); return true; }
  catch { return false; }
}

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: { width: W, height: H },
    deviceScaleFactor: 2,
    recordVideo: { dir: VIDEO_DIR, size: { width: W, height: H } },
  });
  const page = await context.newPage();

  console.log('opening dashboard...');
  await page.goto(FRONTEND, { waitUntil: 'load', timeout: 60000 });
  await sleep(3000);

  // --- Intro ---
  await caption(page, 'CrisisPilot — Autonomous AI Incident Commander', 'Demo');
  await sleep(7000);
  await caption(page, 'Gemini  ·  Google Cloud Agent Builder (ADK)  ·  Dynatrace MCP', 'Stack');
  await sleep(8000);

  // --- Incident 1 ---
  await caption(page, 'Incident detected — spinning up the AI war-room', 'Detect');
  if (!(await clickByText(page, 'Trigger incident'))) await apiTrigger('incident 1');
  await sleep(9000);
  await caption(page, '5 specialized agents investigate in parallel — each a real ADK LlmAgent', 'Agent Builder');
  await sleep(13000);
  await caption(page, 'Reasoning generated by Gemini, streamed token-by-token', 'Gemini');
  await sleep(11000);

  // --- War-room: Dynatrace MCP ---
  await caption(page, 'Agents query Dynatrace Grail live via the Dynatrace MCP server', 'Dynatrace MCP');
  await pan(page, 650, 13);
  await sleep(4000);
  await caption(page, 'Real execute_dql calls — dynatrace.query & dynatrace.deployments', 'Dynatrace MCP');
  await sleep(7000);
  await pan(page, -650, 11);
  await sleep(3000);

  // --- Synthesis & impact ---
  await caption(page, 'Root cause synthesized · remediation proposed for approval', 'Synthesis');
  await sleep(10000);
  await caption(page, 'Business impact quantified in real time', 'Impact');
  await pan(page, 350, 7);
  await sleep(6000);
  await pan(page, -350, 7);
  await sleep(3000);

  // --- Incident 2 (breadth) ---
  await caption(page, 'A second incident arrives — handled concurrently', 'Scale');
  await apiTrigger('incident 2');
  await sleep(14000);
  await caption(page, 'Each incident gets its own autonomous investigation', 'Agent Builder');
  await sleep(10000);

  // --- Navigate history ---
  await caption(page, 'Full incident history, timeline, and confidence evolution', 'War room');
  await clickByText(page, 'failures');
  await sleep(7000);
  await clickByText(page, 'latency');
  await sleep(7000);

  // --- Outro ---
  await caption(page, 'CrisisPilot — github.com/gyamini25/crisispilot', 'Open source');
  await sleep(8000);

  console.log('saving video...');
  await context.close();
  await browser.close();
  console.log('done');
})().catch((e) => { console.error('RECORD_ERROR', e); process.exit(1); });
